#!/bin/env bash
touch bashbox
chmod +x bashbox
echo "#""!"/bin/env bash >> bashbox
echo cmdf="$"1 >> bashbox
echo shift >> bashbox
git clone https://github.com/Pan00Pernicek/bashbox/ bashboxmerge
cd bashboxmerge
cd bin
items=$(ls)
cd ..
cd ..
for i in $items
do
 echo if "[" "$"cmdf = $i "]"";"" then" >> bashbox
 #start of text edit
 filern=bashboxmerge/bin/$i
 lines=$(cat $filern | wc -l)
 for u in `seq $lines`
 do
  rn=" "$( head -n $u $filern | tail -1)
  cat <<< "$rn" >> "bashbox"
 done
 echo fi >> bashbox 
done
