#!/usr/bin/env bash
cmdf="$1"
shift
if [ $cmdf = arch ]; then
 printf '%s\n' "${MACHTYPE%%-*}"
fi
if [ $cmdf = basename ]; then
 for file in "$@"; do
    file="${file%/}"
    printf '%s\n' "${file##*/}"
 done
fi
if [ $cmdf = cat ]; then
 for file in "$@"; do
     [[ ! -f $file ]] && {
         printf '%s\n' "cat: $file: No such file or directory." >&2
         exit 1
     }
 
     printf '%s\n' "$(<"$file")"
 done
fi
if [ $cmdf = date ]; then
 date_format="$@"
 
 [[ ${date_format:0:1} == + ]] &&
     date_format="${date_format/+}"
 
 printf "%($date_format)T\\n"
fi
