#!/usr/bin/env bash
rm bxlib
touch bxlib
chmod +x bxlib
echo "#""!"/usr/bin/env bash >> bxlib
cd bin
items=$(ls)
help=$(echo *)
cd ..
for i in $items
do
 echo "bashbox_$i() {" >> bxlib
 echo "alias $i=bashbox_$i" >> bx_alias_tmp
 #start of text edit
 filern=bin/$i
 lines=$(cat $filern | wc -l)
 for u in `seq $lines`
 do
  rn="	"$( head -n $u $filern | tail -1)
  cat <<< "$rn" >> "bxlib"
  echo merging line $u in $i
 done
 echo "}" >> bxlib
done
cat bx_alias_tmp >> bxlib
rm bx_alias_tmp
