#!/usr/bin/env bash
rm bx_tmp_include
touch bx_tmp_include
chmod +x bx_tmp_include
echo "#""!"/usr/bin/env bash >> bx_tmp_include
cd bin
items=$(ls)
help=$(echo *)
cd ..
for i in $items
do
 echo "bashbox_$i() {" >> bx_tmp_include
 echo "alias $i=bashbox_$i" >> bx_alias_tmp
 #start of text edit
 filern=bin/$i
 lines=$(cat $filern | wc -l)
 for u in `seq $lines`
 do
  rn="	"$( head -n $u $filern | tail -1)
  cat <<< "$rn" >> "bx_tmp_include"
  echo merging line $u in $i
 done
 echo "}" >> bx_tmp_include
done
cat bx_alias_tmp >> bx_tmp_include
rm bx_alias_tmp
mv $1 "$1_bx_tmp_copy"
mv bx_tmp_include $1
cat "$1_bx_tmp_copy" >> $1
rm bx_tmp_copy
