#!/usr/bin/env bash
if [ $1 = arch ]; then
 printf '%s\n' "${MACHTYPE%%-*}"
fi
if [ $1 = basename ]; then
 for file in "${@: +1}"; do
    file="${file%/}"
    printf '%s\n' "${file##*/}"
 done
fi
if [ $1 = cat ]; then
 for file in "${@: +1}"; do
     [[ ! -f $file ]] && {
         printf '%s\n' "cat: $file: No such file or directory." >&2
         exit 1
     }
 
     printf '%s\n' "$(<"$file")"
 done
fi
if [ $1 = date ]; then
 date_format="${@: +1}"
 
 [[ ${date_format:0:1} == + ]] &&
     date_format="${date_format/+}"
 
 printf "%($date_format)T\\n"
fi
