#!/usr/bin/env bash
bashbox_build=$(date +%s)
bin() {
	rm bashbox
	touch bashbox
	chmod +x bashbox
	echo "#""!"/usr/bin/env bash >> bashbox
	echo cmdf="$"1 >> bashbox
	echo shift >> bashbox
	cd bin
	items=$(ls)
	help=$(echo *)
	cd ..
	echo if "[[" "$"cmdf = "--build" "]]"";"" then" >> bashbox
	echo "	"echo $bashbox_build >> bashbox
	for i in $items
	do
		echo elif "[[" "$"cmdf = $i "]]"";"" then" >> bashbox
		#start of text edit
		filern=bin/$i
		lines=$(cat $filern | wc -l)	
		for u in `seq $lines`
		do
			rn="	"$( head -n $u $filern | tail -1)
			cat <<< "$rn" >> "bashbox"
			echo merging line $u in $i
		done
	done
	echo else >> bashbox
	echo " "echo $help  >> bashbox
	echo fi >> bashbox
}
fast-bin() {
	rm bashbox
	touch bashbox
	chmod +x bashbox
	echo "#""!"/usr/bin/env bash >> bashbox
	echo cmdf="$"1 >> bashbox
	echo shift >> bashbox
	cd bin
	items=$(ls)
	help=$(echo *)
	cd ..
	echo if "[[" "$"cmdf = "--build" "]]"";"" then" >> bashbox
	echo "	"echo $bashbox_build >> bashbox
	for i in $items
	do
		echo elif "[[" "$"cmdf = $i "]]"";"" then" >> bashbox
		#start of text edit
		cat bin/$i >> bashbox
		echo merging file $i
	done
	echo else >> bashbox
	echo " "echo $help  >> bashbox
	echo fi >> bashbox
}
lib() {
	rm bxlib
	touch bxlib
	chmod +x bxlib
	echo "#""!"/usr/bin/env bash >> bxlib
	echo "bashbox_build=$bashbox_build" >> bxlib
	cd bin
	items=$(ls)
	help=$(echo *)
	cd ..
	for i in $items
	do
		echo "bashbox_$i() {" >> bxlib
		echo "alias $i=bashbox_$i" >> bx_alias_tmp
		#start of text edit
		filern=bin/$i
		lines=$(cat $filern | wc -l)
		for u in `seq $lines`
		do
			rn="	"$( head -n $u $filern | tail -1)
			cat <<< "$rn" >> "bxlib"
			echo merging line $u in $i
		done
		echo "}" >> bxlib
	done
	cat bx_alias_tmp >> bxlib
	rm bx_alias_tmp
}
fast-lib() {
	rm bxlib
	touch bxlib
	chmod +x bxlib
	echo "#""!"/usr/bin/env bash >> bxlib
	echo "bashbox_build=$bashbox_build" >> bxlib
	cd bin
	items=$(ls)
	help=$(echo *)
	cd ..
	for i in $items
	do
		echo "bashbox_$i() {" >> bxlib
		echo "alias $i=bashbox_$i" >> bx_alias_tmp
		#start of text edit
		cat bin/$i >> bxlib
		echo merging file $i
		echo "}" >> bxlib
	done
	cat bx_alias_tmp >> bxlib
	rm bx_alias_tmp
}
for action in "$@"
do
	$action
done
